name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  AZURE_WEBAPP_NAME: 'waiteconfig'
  AZURE_WEBAPP_PACKAGE_PATH: './wwwroot.zip'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: .

    - name: Download artifact for deployment job
      uses: actions/download-artifact@v2
      with:
        name: app
        path: .

    - name: Install zip package
      run: sudo apt-get install zip

    - name: Zip the app content
      run: |
        cd $GITHUB_WORKSPACE/wwwroot
        zip -r ../wwwroot.zip .

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1.0.0-preview8
      with:
        azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "/" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
        app_build_command: "npm install && npm run build"
        ###### Deployment Configurations ######
        # For more information regarding Azure Static Web App deployment configurations, please visit: https://aka.ms/swadeployconfig
        azure_static_web_apps_environment: production
        azure_static_web_apps_api_environment: production
        ###### End of Deployment Configurations ######
        package_path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      shell: bash

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
